<p>Practice on PHP</p>
<?php
$tree = array("TREES CLEAN THE AIR","TREES PROVIDE OXYGEN","TREES COOL THE STREETS AND THE CITY"
,"TREES SAVE WATER","TREES HELP PREVENT SOIL EROSION","TREES BRING DIVERSE GROUPS OF PEOPLE TOGETHER",
"TREES PROVIDE WOOD","TREES CREATE ECONOMIC OPPORTUNITIES","TREES HELP PREVENT WATER POLLUTION","TREES ARE TEACHERS AND PLAYMATES");

for($i =0;$i<10;$i++)
{
	echo "<li>";
	echo $tree[$i];
	echo "</li>";
	
}
?>
